#!/bin/sh

while read file
do
	fullpath="$(pwd)/$file"
	case "$1" in
	"o")
		mpv "$(echo $file | sed 's/\..*$/.mp4/')" ||
		mpv "$(echo $file | sed 's/\..*$/.webm/')" ||
		mpv "$file" & ;;
	esac
done
