#!/bin/sh

while read file
do
	fullpath="$(pwd)/$file"
	case "$1" in
	"o")
		mpv --script-opts=autoload-disabled=yes "$(echo $file | sed 's/\/.cache//' | sed 's/.jpg/.mp4/' | sed 's/.png/.mp4/')" ||
		mpv --script-opts=autoload-disabled=yes "$file" & ;;
	esac
done
