#!/bin/sh

while read file
do
	fullpath="$(pwd)/$file"
	case "$1" in
	"o")
		mpv --script-opts=autoload-disabled=yes "$(echo $file | sed 's/\..*$/.mp4/')" ||
		mpv --script-opts=autoload-disabled=yes "$(echo $file | sed 's/\..*$/.webm/')" ||
		mpv --script-opts=autoload-disabled=yes $file & ;;
	esac
done
