#!/bin/bash

IFS=$'\n'
dir="$*"
if [ -z "$*" ]; then dir="$PWD"; fi

for f in $(find $dir -name '*.mp4' -or -name '*.webm'); do
	cache="$(dirname "$f")/.cache"
	if [ ! -d $cache ]; then mkdir $cache; fi
	ffmpeg -v quiet -y -ss 00:00:00 -i "$f" -vframes 1 -filter:v scale="160:-1" "$cache/$(basename "$f" | sed 's/\..*$/.png/')"
done
find $dir -type f \( -iname \*.jpg -o -iname \*.png \) -printf '%f %p\n' | sort -nrk1,1 | cut -f 2- -d ' ' | sxiv -t -i
